In [90]:
print("hello wrld \n haha")
# im just messing around here

hello wrld 
 haha


In [91]:
a=3

print(a)

3


In [92]:
b=10

print(b-a)

7


In [93]:
c=b/a


print(int(c))
print(c!=a)


3
True


In [94]:
a = a+1
print(a)
# to here.


4


In [95]:
a = 10
a = a+1
print(a)

b = 10
b = b+2
print(b)

11
12


In [96]:
name = "Jay"
fix = "walker"
print("U R goddamn "+name+fix+" haha")

U R goddamn Jaywalker haha


In [97]:
print("name")

name


In [98]:
print(Jay)

# yeah the PC really fricked out this time.

NameError: name 'Jay' is not defined

In [103]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
36


In [111]:
import this
print(this.s)

Gur Mra bs Clguba, ol Gvz Crgref

Ornhgvshy vf orggre guna htyl.
Rkcyvpvg vf orggre guna vzcyvpvg.
Fvzcyr vf orggre guna pbzcyrk.
Pbzcyrk vf orggre guna pbzcyvpngrq.
Syng vf orggre guna arfgrq.
Fcnefr vf orggre guna qrafr.
Ernqnovyvgl pbhagf.
Fcrpvny pnfrf nera'g fcrpvny rabhtu gb oernx gur ehyrf.
Nygubhtu cenpgvpnyvgl orngf chevgl.
Reebef fubhyq arire cnff fvyragyl.
Hayrff rkcyvpvgyl fvyraprq.
Va gur snpr bs nzovthvgl, ershfr gur grzcgngvba gb thrff.
Gurer fubhyq or bar-- naq cersrenoyl bayl bar --boivbhf jnl gb qb vg.
Nygubhtu gung jnl znl abg or boivbhf ng svefg hayrff lbh'er Qhgpu.
Abj vf orggre guna arire.
Nygubhtu arire vf bsgra orggre guna *evtug* abj.
Vs gur vzcyrzragngvba vf uneq gb rkcynva, vg'f n onq vqrn.
Vs gur vzcyrzragngvba vf rnfl gb rkcynva, vg znl or n tbbq vqrn.
Anzrfcnprf ner bar ubaxvat terng vqrn -- yrg'f qb zber bs gubfr!


In [106]:
print(type(c))
print(type(name))

<class 'float'>
<class 'str'>


In [117]:
me = "나는"
age = "40살입니다."
print(me+" "+age+"\n사실 구라지롱")

나는 40살입니다.
사실 구라지롱


In [118]:
fage = 40
print(me+" "+fage+"\n사실 구라지롱")

TypeError: can only concatenate str (not "int") to str

In [121]:
input()

hehe


'hehe'

In [130]:
from datetime import datetime

birth_year = int(input("Type your birth year:"))
year = datetime.today().year
age = year - birth_year
print("Your age is:", age)
print(year)

Type your birth year:2001
Your age is: 21
2022


In [134]:
a = 10
print(a == 10)

True


In [136]:
true = True
true == 1

True

In [1]:
print(bool(""))
print(bool("1"))
print(bool(0))
print(bool(1))

False
True
False
True


In [3]:
4//2 == 2

True

In [4]:
not(5>3) or 3!=5

True

In [5]:
not False

True

In [8]:
not(not(5>3)) or 3!=5

True

In [ ]:
not(not(5>3)) or 3!=5

In [9]:
True or True

True

In [10]:
True or False and False

True

In [13]:
print(ord("A"))
print(ord("B"))
print(ord("C"))

print(ord("A"))
print(ord("A"))
print(ord("A"))

65
66
67


In [16]:
a = 1

a += 1

print(a)

2


In [22]:
list = [10, 20, 30, 40, 50]  #시퀀스(시간의 흐름에 따름) 자료형.
                     #특징/공통점: 인덱스. 0번부터 순서를 매김

print(len(list))
# print(a[1:3])
# print(a[1])

print(type(list))

5
<class 'list'>


In [26]:
sub = ["국어", "영어", "수학", ["생물", "화학"]]

print(sub[3])
print(sub[3][1])
print(len(sub))

['생물', '화학']
화학
4


In [36]:
blpin = []
blpin.append("Lisa")
blpin.append("Zenny")
blpin.append("Wanze")
blpin.append("Zisu")
print("Weird assemble")
print(blpin, "\n")

blpin [2] = "Roze"
print("Replace someone")
print(blpin, "\n")

blpin.insert(1, "Wanze")
print("Added weirdo again")
print(blpin, "\n")

blpin.sort()
print("Sorting...")
print(blpin, "\n")

blpin.remove("Wanze")
print("Remove Wanze")
print(blpin, "\n")

print("Is there any weirdo?")
print("Wanze" in blpin)

Weird assemble
['Lisa', 'Zenny', 'Wanze', 'Zisu'] 

Replace someone
['Lisa', 'Zenny', 'Roze', 'Zisu'] 

Added weirdo again
['Lisa', 'Wanze', 'Zenny', 'Roze', 'Zisu'] 

Sorting...
['Lisa', 'Roze', 'Wanze', 'Zenny', 'Zisu'] 

Remove Wanze
['Lisa', 'Roze', 'Zenny', 'Zisu'] 

Is there any weirdo?
False


In [49]:
a = "Black Pink"
print("[4:9]")
print(a[4], a[9], "\n")

print("[0:5]")
print(a[0:5], "\n")
      
print("[6:]")
print(a[6:], "\n")

b = " love"
print("BP + L")
print(a+b, "\n")

print(" L L L")
print(b * 3, "\n")

print("How long is \"a?\"")
print(len(a), "\n")

print("Is there \"a\" in Black?")
print("a" in "Black")

[4:9]
k k 

[0:5]
Black 

[6:]
Pink 

BP + L
Black Pink love 

 L L L
 love love love 

How long is "a?"
10 

Is there "a" in Black?
True


In [52]:
print(len(dir(str))) #Use cheatsheet U dickhead or stack overflow or github or urdad

80


In [ ]:
# help()

In [1]:
a = "Black Pink"
a.split()
print(a)


#####IT DOSENT WORK
#NVM the kernal was busy as hell

Black Pink


In [2]:
a = "Black Pink"
a = a.lower()
print(a)

b = a.upper()
print(b)

black pink
BLACK PINK


In [4]:
print("%d" % 1000)

1000


In [5]:
print("%d" % 100.123)

100


In [8]:
a= 123.456789
print("%f" % a)
print("%.10f" % a)
print("%.2f" % a)
print("%.3f" % a)
print("%d" % a)

123.456789
123.4567890000
123.46
123.457
123


In [9]:
print("나는 오늘 %d번 밥을 먹었습니다. 지금 %s이 먹고 싶어요." % (5, "밥"))

나는 오늘 5번 밥을 먹었습니다. 지금 밥이 먹고 싶어요.


In [11]:
print("오늘 날씨는 {}이고, 기온은 {}도입니다." .format("sunny", 28))

오늘 날씨는 sunny이고, 기온은 28도입니다.


In [14]:
print("오늘 날씨는 {0}이고, 기온은 {1}도입니다." .format("sunny", 28))

오늘 날씨는 sunny이고, 기온은 28도입니다.


In [15]:
print("오늘 날씨는 {weather}이고, 기온은 {deg}도입니다." .format(deg=28, weather="sunny"))

오늘 날씨는 sunny이고, 기온은 28도입니다.


In [23]:
print('\tShoutout \nto \n\t\"simpleflips\"')

##Be careful about same thing

	Shoutout 
to 
	"simpleflips"


In [1]:
Tot = ('Son', 'Kein')
Tot[1] = 'Salla'

# TypeError: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

In [3]:
a = 1
b = 2

a, b = b, a
print(a)
print(b)

##############왜 이런 짓을

2
1


In [71]:
if True:
    print("조건문을 실행합니다.")

조건문을 실행합니다.


In [74]:
x = 3
if x % 2 == 0:   #0이면 당연히 짝수
    print(x, "는 짝수입니다")
print("몰루")

몰루


In [76]:
x = 3
if x % 2 == 0:   #0이면 당연히 짝수
    print(x, "는 짝수입니다")
if x % 2 != 0:
    print(x, "는 홀수입니다")

3 는 홀수입니다


In [77]:
x = 7

if x % 2 == 0:
    print(x, "는 짝수입니다")
    
else:
    print(x, "는 홀수입니다")

7 는 홀수입니다


In [79]:
score = int(input("당신의 점수는: "))

if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
else:
    print("D")

당신의 점수는: 80
B


In [80]:
i = 0
while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


In [85]:
i = 1
sum_ = 0

while i <= 10:
    sum_ = sum_ + 1
    print(sum_)
    i = i + 1
    
print("\n", sum_)

1
2
3
4
5
6
7
8
9
10

 10


In [87]:
a = [1,2,3,4,5,6,7,8,9,10]
sum(a)

55

In [89]:
pwd = "0000"

while pwd !="1234":
    pwd = input("비밀번호는: ")
print("어서오세요")

비밀번호는: 12345
비밀번호는: 477375
비밀번호는: 
비밀번호는: 1234
어서오세요


In [90]:
for i in [0,1,2,3,4,5,6,7,8,9]:
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [91]:
blackpink = ["Zenny", "Zisu", "Rose", "Lisa"]
for member in blackpink:
    print (member)

Zenny
Zisu
Rose
Lisa


In [92]:
for letter in "Python":
    print(letter)

P
y
t
h
o
n


In [93]:
for i in range(0, 10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [94]:
for i in range(10):
    print('hi', end=' ')

hi hi hi hi hi hi hi hi hi hi 

In [96]:
for i in range(1, 10, 2):   ##1부터 10 미만까지 2씩 증가
    print(i, end=' ')

1 3 5 7 9 

In [97]:
for i in range(5):
    print(i, "hello")

0 hello
1 hello
2 hello
3 hello
4 hello


In [8]:
score = enumerate([55, 70, 92, 88])
for i, value in score:
    print(i, ":", value)

0 : 55
1 : 70
2 : 92
3 : 88


In [9]:
score = [55, 70, 92, 88]

number = 0
for i in score:
    number = number + 1
    if i >= 90:
        print("%d번째 과목은 A." % number)
    elif i >= 80:
        print("%d번째 과목은 B." % number)
    elif i >= 70:
        print("%d번째 과목은 C." % number)
    else:
        print("%d번째 과목은 D." % number)

1번째 과목은 D.
2번째 과목은 C.
3번째 과목은 A.
4번째 과목은 B.


In [10]:
blackpink = ["Zenny", "Zisu", "Rose", "Lisa"]
for member in blackpink:
    print(member)
    for name in member:
        print(name)

Zenny
Z
e
n
n
y
Zisu
Z
i
s
u
Rose
R
o
s
e
Lisa
L
i
s
a


In [3]:
for i in range (2, 6, 1):
    print(i)                 #다중 for문
    for j in range(1, 6, 1):
        print(i, "*", j, "=", i*j)

2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
4
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25


In [7]:
i = 2

while i < 6:
    print(i)
    j = 1
    while j < 6:
        print(i, "*", j, "=", i*j)
        j = j + 1
    i = i + 1

2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
4
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25


In [1]:
i = 0
while i<10:
    print(i, end = " ")
    i= i + 1

0 1 2 3 4 5 6 7 8 9 

In [2]:
i = 0
while True:
    print(i, end = " ")
    i= i + 1
    if i >= 10:
        break  ##돔황챠~~~

0 1 2 3 4 5 6 7 8 9 

In [8]:
for i in range(1, 10):
    if i % 2 == 0:
        print(i)

2
4
6
8


In [10]:
for i in range(1, 10):
    if i % 2 != 0:
        continue
    print(i)

2
4
6
8


In [14]:
bprv = [["Zenny","Irin"],["Rose","Wendy", "Lollo"],["Lisa", "Sulgui"],["Zisu", "Zoy"]]  ## Who is Lollo?
        
bp = [i[0] for i in bprv]
rv = [i[1] for i in bprv]
        
print(bp)
print(rv)

['Zenny', 'Rose', 'Lisa', 'Zisu']
['Irin', 'Wendy', 'Sulgui', 'Zoy']


In [16]:
a = [[1, 11], [2, 22], [3,33], [4,44], [5,55]]
x = [i[0] for i in a if i[0] > 3]
y = [i[1] for i in a if i[1] % 2 != 0]

print(x)
print(y)

[4, 5]
[11, 33, 55]


In [30]:
def im ():
        print("My name is %s, Age is %d." % ('Jay', 20))
        print('Hobby is {} and {}.' .format('reading', 'movie'))
        print("aaaaa")
        
im()

My name is Jay, Age is 20.
Hobby is reading and movie.
aaaaa


In [32]:
def hate_repeat (something):
    print(something)
    print(something)
    
hate_repeat("fuk you")

fuk you
fuk you


In [36]:
def 더하기 (n1, n2):
    sum1 = n1 + n2
    return sum1
print(더하기(20, 30))

result = 더하기(1, 2)
print(result)

50
3


In [40]:
def OR(x1, x2):
    if x1 == 1:
        return 1
    elif x2 == 1:
        return 1
    else:
        return 0
    
OR(0,1)

1

In [44]:
def greet(name, hello=2): ##default count, hello has 2 in default.
    for i in range(hello):
        print(name, "hi")
        
greet("Jay", 16)

Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi
Jay hi


In [45]:
x = 1 #global

def func1():
    x = 2  #not global
    return x

print(func1())
print(x)

2
1


In [46]:
a = 1 #global

def func2():
    global a  #now it is a global
    a = 2  
    return a

print(func2())
print(a)

2
2


    여기서부터 과제 나감(지역변수 이후 람다)

In [1]:
더하기 = lambda a, b : a + b
a = 더하기 (1,2)
print(a)

3


In [2]:
f = lambda x : x +1
for i in range(3):
    print(f(i))

1
2
3


In [3]:
##### CLASS IS IMPORTANT!!!!!!!!!!!!!!!!!!!!!!!!!

class Cat :
    kind = "코숏"
    name = "코코"
    
coco = Cat()

In [4]:
coco.kind

'코숏'

In [5]:
print(coco.name)

코코


In [6]:
coco.kind = "코리안 숏헤어"
coco.kind

'코리안 숏헤어'

In [12]:
class Cat :
    kind = "코숏"
    name = "코코"

    def hello (self) :
        print("Meow")
        print("Mwi naweme iss "+self.name+". MewMew")

In [13]:
coco = Cat()
coco.hello()

Meow
Mwi naweme iss 코코. MewMew


In [17]:
class Cat :
    def __init__(self, kind, name):
        self.kind = kind
        self.name = name
        print("MewMeww")

    def hello (self) :
        print("Eye amm "+self.kind+". Meow")
        print("And Mwi naweme iss "+self.name+". MewMew")

In [18]:
coco = Cat ("British shorthair", "Boksoon")

MewMeww


In [19]:
coco.hello()

Eye amm British shorthair. Meow
And Mwi naweme iss Boksoon. MewMew


In [216]:
class Robot:
    def __init__(self, IQ):
        self.IQ = IQ
        print("Hello. Thanks for creating me.")
        
    def train (self):
        self.IQ *= 2
        if self.IQ < 10000:
            print(f"My currunt IQ is {self.IQ}. I'm an idiot.")
        else:
            print(f"My IQ achieve {self.IQ}. I hate you")

In [217]:
humanoid = Robot(50)

Hello. Thanks for creating me.


In [5625]:
humanoid.train()

My IQ achieve 71237164483277548443485606310361739490388951861675542113476258776464443189863289939403173117159434368385388609290746811957491309919430007648750521669132754421781700480372794100318484320853962111600589510578736695557997516340748787588182388044813572215678493550476010412326366774924291336684950603909437356735505796225573562914286109385238583606797692515755321224746400347237726994049895060835532686982117849354710494886998695381464492944062686613991530430087527110406663920149965389164182667692119342622798157256512004519343935245167456785253413373904816252283277076783018918710314046343962957551201234109351525291594089189650632199692053985550865374352604860595667072800533466087607647056775281292932330536504326049246582009798117472300899455712145720450970144212479011631857436455005060486546935967950163107380617018591500702364611625795155747918733339336251594723670034769159201082108262247759492581233975449985934262740986413680263148919620082795796789665451990028912066725786735772

In [330]:
class Plus(Plus_Minus):             ##### I ADDED Plus_Minus THINGY
    def plus(self, n1, n2):
        return n1+n2
    
class Plus_Minus(Plus):
    def minus (self, n3, n4):
        return n3-n4
    
a = Plus()
print(a.plus(1, 2))

3


In [331]:
b = Plus_Minus()
print(b.plus(1,2))

3


In [332]:
print(b.minus (3,4))

-1


In [333]:
print(a.minus (3,4))    ##It didn't even auto-correct the a.minus

-1


In [5637]:
from random import randint
randint(1, 10)

2

In [5638]:
from random import *
randint(1, 10)

2

In [5639]:
import random as rd
rd.randint(1, 10)

3

In [5641]:
import random
random.randint(1, 10)

10

In [5642]:
lotto_num = list(range(1, 46))
print(lotto_num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]


In [5730]:
import random
lotto = random.sample(lotto_num, 6)

lotto.sort()
print("이번 주 추천번호는: ", lotto)

이번 주 추천번호는:  [8, 13, 14, 32, 33, 37]


In [5732]:
f = open("test1.txt", "w", encoding="utf-8")  ##인코딩은 한글처리
f.write("안녕하세요?\n")
f.write("고맙습니다.")
f.close()

In [5736]:
text = input()
f = open ("test2.txt", "w", encoding="utf-8")
f.write (text)
f.close

hehe sneaky text 안녕하세요 텍스트입니다.


<function TextIOWrapper.close()>

In [5737]:
f = open("test1.txt", "r", encoding="utf-8")
g = open ("text_copyeee.txt", "w", encoding="utf-8")

data = f.read()
g.write(data)

f.close()
g.close()


##################################6과######################################






In [5]:
import numpy as np

# np.arange(start= 1, stop= 11, step= 2)
np.arange(1, 12, 3)

array([ 1,  4,  7, 10])

In [6]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((4,5), dtype="int32")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
arr1 = np.arange(1,5)
arr1[0]

1

In [15]:
arr1[-1]

4

In [17]:
arr1[2:]

array([3, 4])

In [22]:

arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
arr4[2,2]

9

In [24]:
arr4[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [25]:
A = np.array([0,1,2,3,4,5,6,7,8,9])

arr5 = A.reshape(2,5)
arr6 = A.reshape(5,2)
print(arr5)
print(arr6)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [28]:
A.reshape(3,3)  ##hehe

ValueError: cannot reshape array of size 10 into shape (3,3)

In [29]:
arr7 = A.reshape(2,-1)
arr8 = A.reshape(-1,2)
print(arr7)
print(arr8)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
arr7.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [33]:
arr8.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [34]:
 arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr4[[0],[0,2]]

array([1, 3])

In [36]:
arr4[[1,2],:]

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
B = np.array([3,2,1,4,0])
np.sort(B)

array([0, 1, 2, 3, 4])

In [38]:
arr4 > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [39]:
C = np.array([[2, 4], [5, 1]])
np.sort(C, axis = 1)

array([[2, 4],
       [1, 5]])

In [40]:
np.sort(C, axis = 0)

array([[2, 1],
       [5, 4]])

In [42]:
############BROADCAST
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])


a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [43]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [44]:
a + np.array([0.1,0.2,0.3])

array([[1.1, 2.2, 3.3],
       [4.1, 5.2, 6.3]])

In [46]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[2,3],[3,4]])

np.dot(A,B)

array([[14, 20],
       [32, 47]])